# 基于ubuntu 16.04制作 django_uwsgi_nginx一体的镜像
# 参考：https://blog.csdn.net/qq_36792209/article/details/82778611   https://blog.csdn.net/qq_31325495/article/details/88891525
# 预定义的目录 /data/apps/mysite /data/tmp/sock /data/tmp/pid /data/logs/uwsgi /data/logs/nginx



FROM ubuntu:16.04
 
RUN mkdir -p /data/apps/mysite /data/tmp/sock /data/tmp/pid /data/logs/uwsgi /data/logs/nginx /data/logs/supervisor

WORKDIR /data/apps/mysite

COPY ./ ./

COPY docker/pip.conf /root/.pip/pip.conf

ADD docker/sources.list /etc/apt/sources.list
 
RUN apt-get -y update && \
	apt-get upgrade -y && \ 
	apt-get install -y nginx supervisor vim python3 python3-dev python3-pip python3-setuptools sqlite3 && \
 	pip3 install -U pip setuptools && \
 	pip3 --no-cache-dir install uwsgi && \
 	pip3 --default-timeout=100 --no-cache-dir install -r /data/apps/mysite/requirements.txt && \
	ln -s /data/apps/mysite/docker/mysite_nginx.conf /etc/nginx/sites-enabled/ && \
	ln -s /data/apps/mysite/docker/supervisord.conf /etc/supervisor/conf.d/ && \
	apt-get clean all 
 
WORKDIR /data
 
CMD ["/usr/bin/supervisord", "-n"]
